version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${PG_DATABASE:-question_pro}
      POSTGRES_USER: ${PG_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-iauro@100}
    ports:
      - "${PG_PORT:-5432}:5432"
    networks:
      - nest-network

  # NestJS application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      NODE_ENV: development
      DB_TYPE: postgres
      PG_HOST: db
      PORT: 3000
      PG_PORT: 5432
      PG_USERNAME: ${PG_USERNAME:-postgres}
      PG_PASSWORD: ${PG_PASSWORD:-iauro@100}
      PG_DATABASE: ${PG_DATABASE:-question_pro}
      SWAGGER_BASEPATH: 
      SWAGGER_TITLE: Grocery feature microservice
      SWAGGER_DESC: The Grocery feature microservice api description
      SWAGGER_VERSION: 1.0
      SWAGGER_TAG: Grocery feature microservice
      SWAGGER_DOC_PATH: api/documentation
    ports:
      - "3000:3000"
    networks:
      - nest-network

networks:
  nest-network:
    driver: bridge